name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI_Checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install and Run staticcheck
      run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

    - name: Install and Run golint
      run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

    - name: Install and Check for unhandled error
      run: |
          go install github.com/kisielk/errcheck@latest
          errcheck ./...

    - name: Run tests
      run: go test -race -vet=off ./...
